workflows:
  android-release:
    name: Build Android APK
    max_build_duration: 15
    environment:
      node: 18
      java: 11
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
